//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Patientportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PatientRxData
    {
        public int PatientRxData_ID { get; set; }
        public int Patient_ID { get; set; }
        public int RxData_ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual TB_Patient TB_Patient { get; set; }
        public virtual TB_RxData TB_RxData { get; set; }
    }
}
