//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Patientportal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RxData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_RxData()
        {
            this.TB_PatientRxData = new HashSet<TB_PatientRxData>();
        }
    
        public int RxData_ID { get; set; }
        public System.DateTime RxDate { get; set; }
        public string RxDoctor { get; set; }
        public string Prescription1 { get; set; }
        public string Prescription2 { get; set; }
        public string Prescription3 { get; set; }
        public string Prescription4 { get; set; }
        public string Prescription5 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PatientRxData> TB_PatientRxData { get; set; }
    }
}
